[package]
org = "samue"
name = "serverTest"
version = "0.1.0"
distribution = "2201.9.2"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
path = "./libs/mysql-connector-j-8.1.0.jar"
